"""create initial schema

Revision ID: a5b3b458aaf8
Revises: 
Create Date: 2026-08-17 22:03:18.820250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b3b458aaf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('patient_reference', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_patient_reference_created_at', 'audit_logs', ['patient_reference', 'created_at'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('facility_type', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_name', sa.String(length=256), nullable=False),
    sa.Column('brand_name', sa.String(length=256), nullable=True),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('form', sa.String(length=64), nullable=True),
    sa.Column('pack_size', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines')),
    sa.UniqueConstraint('generic_name', 'brand_name', 'strength', 'form', 'pack_size', name='uq_medicines_product')
    )
    op.create_table('facility_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=256), nullable=False),
    sa.Column('availability_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_services_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_services')),
    sa.UniqueConstraint('facility_id', 'service_name', name='uq_facility_services_service')
    )
    op.create_index(op.f('ix_facility_services_facility_id'), 'facility_services', ['facility_id'], unique=False)
    op.create_table('medicine_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('jan_aushadhi_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_medicine_prices_medicine_id_medicines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_prices'))
    )
    op.create_index(op.f('ix_medicine_prices_medicine_id'), 'medicine_prices', ['medicine_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_facility_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_facility_id'], ['facilities.id'], name=op.f('fk_patients_current_facility_id_facilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_patients_external_reference'))
    )
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=256), nullable=True),
    sa.Column('history_text', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('previous_treatments', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_records_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_records'))
    )
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('required_service', sa.String(length=256), nullable=False),
    sa.Column('current_facility_id', sa.Integer(), nullable=True),
    sa.Column('recommended_facility_level', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_facility_id'], ['facilities.id'], name=op.f('fk_referrals_current_facility_id_facilities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_referrals_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    op.create_index(op.f('ix_referrals_current_facility_id'), 'referrals', ['current_facility_id'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_table('treatment_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('option_name', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_treatment_predictions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_predictions'))
    )
    op.create_index('ix_treatment_predictions_patient_id_created_at', 'treatment_predictions', ['patient_id', 'created_at'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_record_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reference_range', sa.String(length=256), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], name=op.f('fk_lab_results_clinical_record_id_clinical_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_results'))
    )
    op.create_index(op.f('ix_lab_results_clinical_record_id'), 'lab_results', ['clinical_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_results_clinical_record_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index('ix_treatment_predictions_patient_id_created_at', table_name='treatment_predictions')
    op.drop_table('treatment_predictions')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_current_facility_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medicine_prices_medicine_id'), table_name='medicine_prices')
    op.drop_table('medicine_prices')
    op.drop_index(op.f('ix_facility_services_facility_id'), table_name='facility_services')
    op.drop_table('facility_services')
    op.drop_table('medicines')
    op.drop_table('facilities')
    op.drop_index('ix_audit_logs_patient_reference_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
